// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using UnityEngine;

namespace Navigation {

		[TestFixture]
		public class UIManagerTest{
				[Test]
				public void ChangeSceneCorrect (){
					UIManagerScript testObject1 = new UIManagerScript();
					String testLevelName = "TitleScreen";
					testObject1.changeSceneButton(testLevelName);
					String actualLevelName = Application.loadedLevelName;
					
					Assert.AreEqual(testLevelName, actualLevelName);
				}

				[Test]
				public void ChangeSceneNotCorrect (){
					UIManagerScript testObject2 = new UIManagerScript();
					String testLevelName = "LessonMenu";
					String notCorrectName = "not correct";
					testObject2.changeSceneButton(testLevelName);
					String actualLevelName = Application.loadedLevelName;
			
					Assert.AreNotEqual(notCorrectName , actualLevelName);
				}

				[Test]
				public void ChangeSceneNotRealLevelName (){
					UIManagerScript testObject3 = new UIManagerScript();
					String testLevelName = "NotARealLevelName";
					testObject3.changeSceneButton(testLevelName);
					String actualLevelName = Application.loadedLevelName;

					Assert.AreNotEqual(testLevelName , actualLevelName);
				}
		}
}

