// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using UnityEngine;

namespace Navigation {

		[TestFixture]
		public class UIManagerTest{
				[Test]
				public void ChangeSceneCorrect (){
					UIManagerScript testObject1 = new UIManagerScript();
					String testLevelName = "TitleScreen";
					testObject1.changeSceneButton(testLevelName);
					String actualLevelName = Application.loadedLevelName;
					
					Assert.AreEqual(testLevelName, actualLevelName);
				}


//				[Test]
//				public void ChangeSceneNotCorrect (){
//					UIManagerScript testObject2 = new UIManagerScript();
//					String testLevelName = "LessonMenu";
//					testObject2.changeSceneButton(testLevelName);
//					String actualLevelName = Application.loadedLevelName;
//			
//					Assert.AreEqual("not correct", actualLevelName);
//				}
		}
}

